# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CloudFormation Python Plugin CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ 3.6, 3.7, 3.8 ]
    steps:
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
  os_build:
    env:
      AWS_DEFAULT_REGION: us-east-1
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [ 3.6, 3.7, 3.8, 3.9 ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
        cache: pip
    - name: Install dependencies
      run: |
        pip install --upgrade mypy 'attrs==19.2.0' -r https://raw.githubusercontent.com/aws-cloudformation/aws-cloudformation-rpdk/master/requirements.txt
    - name: Install both plugin and support lib
      run: |
        pip install . src/
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit/
        key: ${{ matrix.os }}-${{ env.pythonLocation }}${{ hashFiles('.pre-commit-config.yaml') }}
    - name: pre-commit checks
      run: |
        pre-commit run --all-files
    - name: End to End Resource Packaging Test Python 3.6
      run: ./e2e-test.sh python36
    - name: End to End Resource Packaging Test Python 3.7
      run: ./e2e-test.sh python37
